### ISSUE TITLE
Be able to share links from 3rd part app

### ISSUE THREAD

**Issue by marcw** [marcw/volte-ios#43]
- [x] Share from 3rd part app
- [ ] Fix crash for some links
- [ ] Change "Sharing" to "Volte"
- [ ] Is it possible to use the preview that iOS generates ?

**Comment by marcw** [comment]
Amazing. It works fine for links that have a preview, but it crash when links doesn't have a preview.
On a side note, would that be possible to use the preview ?

**Comment by Palleas** [comment]
Fixed in #43, closing because the preview deserves its own issue.
